### ISSUE TITLE
`ImportError: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)` after upgrade

### ISSUE THREAD

**Issue by jackklika** [smartystreets/smartystreets-python-sdk#39]
Hey. Sorry for the lack of detail but we are at an app launch event and pushed a last minute change to our backend, and we applied your latest patch which crashed our backend. Here's what I'm seeing in our logs. Nothing else changed besides the version. We are reverting to a previous version.

```
accounts-c5d5596f9-bxznz Process SpawnProcess-1:
accounts-c5d5596f9-bxznz Traceback (most recent call last):
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
accounts-c5d5596f9-bxznz     self.run()
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
accounts-c5d5596f9-bxznz     self._target(*self._args, **self._kwargs)
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
accounts-c5d5596f9-bxznz     target(sockets=sockets)
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
accounts-c5d5596f9-bxznz     return asyncio.run(self.serve(sockets=sockets))
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
accounts-c5d5596f9-bxznz     return loop.run_until_complete(main)
accounts-c5d5596f9-bxznz   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
accounts-c5d5596f9-bxznz     config.load()
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 458, in load
accounts-c5d5596f9-bxznz     self.loaded_app = import_from_string(self.app)
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
accounts-c5d5596f9-bxznz     raise exc from None
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
accounts-c5d5596f9-bxznz     module = importlib.import_module(module_str)
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
accounts-c5d5596f9-bxznz     return _bootstrap._gcd_import(name[level:], package, level)
accounts-c5d5596f9-bxznz   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
accounts-c5d5596f9-bxznz   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
accounts-c5d5596f9-bxznz   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
accounts-c5d5596f9-bxznz   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
accounts-c5d5596f9-bxznz   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
accounts-c5d5596f9-bxznz   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[...]
accounts-c5d5596f9-bxznz     from foo.bar.address_validation_service import AddressValidationService
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/foo/bar/address_validation_service.py", line 4, in <module>
accounts-c5d5596f9-bxznz     from smartystreets_python_sdk import ClientBuilder, StaticCredentials
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/smartystreets_python_sdk/__init__.py", line 14, in <module>
accounts-c5d5596f9-bxznz     from .client_builder import ClientBuilder
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/smartystreets_python_sdk/client_builder.py", line 2, in <module>
accounts-c5d5596f9-bxznz     from smartystreets_python_sdk.us_street import Client as USStreetClient
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/smartystreets_python_sdk/us_street/__init__.py", line 5, in <module>
accounts-c5d5596f9-bxznz     from .lookup import Lookup
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/smartystreets_python_sdk/us_street/lookup.py", line 1, in <module>
accounts-c5d5596f9-bxznz     from smartystreets_python_sdk.us_street.match_type import MatchType
accounts-c5d5596f9-bxznz   File "/usr/local/lib/python3.10/site-packages/smartystreets_python_sdk/us_street/match_type.py", line 1, in <module>
accounts-c5d5596f9-bxznz     from enum import StrEnum
accounts-c5d5596f9-bxznz ImportError: cannot import name 'StrEnum' from 'enum' (/usr/local/lib/python3.10/enum.py)
```

**Comment by jackklika** [comment]
Yeah, everything works on `4.11.12` but not `4.11.14`. Funny enough this happened during a last minute hotfix an hour before a major demonstration for our application -- remember to pin versions everyone!

**Comment by jackklika** [comment]
Yeah, everything works on 4.11.12 but not 4.11.14. Remember to pin versions!!!

**Comment by RyanLCox1** [comment]
If you upgrade to python 3.11 this will work.

**Comment by fsnlarson** [comment]
We are experiencing this as well starting today

**Comment by RyanLCox1** [comment]
I just pushed a new version 4.11.15 that fixes this issue. You can now use python 3.10 again.
